name: ntua_slp_project
channels:
  - conda-forge
dependencies:
  - notebook
  - jupyterlab
  - ipywidgets
  - tqdm
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - transformers
  - nbstripout
  - ffmpeg
  - pip
  - pip:
      - torch
      - torchaudio
      - torchcodec
